import { 
    UnknowType,
    StringType,
    NumberType,
    TransitionType,
    ColorType,
    BooleanType, 
    ArrayNumberType,
    ArrayStringType,
    ScreenAnchorType,
    Vecter2Type,
    VisibilityType,
    ExpressionType,
} from '../types/types';

export const fillExtrusionStyle = {
    layout: {
        'visibility':    VisibilityType
    },
    paint: {
        "fill-extrusion-ambient-occlusion-ground-attenuation":  NumberType,
        "fill-extrusion-ambient-occlusion-ground-radius":       NumberType,
        "fill-extrusion-ambient-occlusion-intensity":           NumberType,
        "fill-extrusion-ambient-occlusion-radius":              NumberType,
        "fill-extrusion-ambient-occlusion-wall-radius":         NumberType,
        "fill-extrusion-base":                                  NumberType,
        "fill-extrusion-cast-shadows":                          BooleanType,
        "fill-extrusion-color":                                 ColorType,
        "fill-extrusion-cutoff-fade-range":                     NumberType, 
        "fill-extrusion-edge-radius":                           NumberType, 
        "fill-extrusion-emissive-strength":                     NumberType,
        "fill-extrusion-flood-light-color":                     ColorType,
        "fill-extrusion-flood-light-intensity":                 NumberType,
        "fill-extrusion-flood-light-wall-radius":               NumberType,
        "fill-extrusion-flood-light-ground-radius":             NumberType,
        "fill-extrusion-flood-light-ground-attenuation":        NumberType,
        "fill-extrusion-height":                                NumberType,
        "fill-extrusion-line-width":                            NumberType,
        "fill-extrusion-opacity":                               NumberType,
        "fill-extrusion-pattern":                               StringType,
        "fill-extrusion-rounded-roof":                          BooleanType,
        "fill-extrusion-translate":                             Vecter2Type,
        "fill-extrusion-translate-anchor":                      ScreenAnchorType,
        "fill-extrusion-vertical-gradient":                     BooleanType,
        "fill-extrusion-vertical-scale":                        NumberType,
        // "fill-extrusion-opacity-transition":                    TransitionType,
        // "fill-extrusion-color-transition":                      TransitionType,
        // "fill-extrusion-translate-transition":                  TransitionType,
        // "fill-extrusion-height-transition":                     TransitionType,
        // "fill-extrusion-base-transition":                       TransitionType,
        // "fill-extrusion-ambient-occlusion-intensity-transition": TransitionType,
        // "fill-extrusion-ambient-occlusion-radius-transition":   TransitionType,
        // "fill-extrusion-ambient-occlusion-wall-radius-transition": TransitionType,
        // "fill-extrusion-ambient-occlusion-ground-radius-transition": TransitionType,
        // "fill-extrusion-ambient-occlusion-ground-attenuation-transition": TransitionType,
        // "fill-extrusion-flood-light-color-transition": TransitionType,
        // "fill-extrusion-flood-light-intensity-transition": TransitionType,
        // "fill-extrusion-flood-light-wall-radius-transition": TransitionType,
        // "fill-extrusion-flood-light-ground-radius-transition": TransitionType,
        // "fill-extrusion-flood-light-ground-attenuation-transition": TransitionType,
        // "fill-extrusion-emissive-strength-transition": TransitionType,
        // "fill-extrusion-line-width-transition": TransitionType,
    }
}