import { 
    UnknowType, 
    StringType, 
    NumberType, 
    BooleanType, 
    Vecter2Type,
    ColorType,
    ExpressionType,
    TransitionType,
    ArrayNumberType,
    ArrayStringType,
    VisibilityType,
    ScreenAnchorType,

    LineJoinType,
    LineCapType,
} from '../types/types';

export const lineStyle = {
    layout: {
        "line-cap":                          LineCapType,
        "line-join":                         LineJoinType,
        "line-miter-limit":                  NumberType,
        "line-round-limit":                  NumberType,
        "line-sort-key":                     NumberType,
        "visibility":                        VisibilityType,
    },
    paint: {
        "line-opacity":                      NumberType,
        "line-color":                        ColorType,
        "line-translate":                    Vecter2Type,
        "line-translate-anchor":             ScreenAnchorType,
        "line-width":                        NumberType,
        "line-gap-width":                    NumberType,
        "line-offset":                       NumberType,
        "line-blur":                         NumberType,
        "line-dasharray":                    ArrayNumberType,
        "line-pattern":                      StringType,
        "line-gradient":                     ExpressionType,
        "line-trim-offset":                  Vecter2Type,
        "line-trim-color":                   ColorType,
        "line-emissive-strength":            NumberType,
        "line-border-width":                 NumberType,
        "line-border-color":                 ColorType,
        "line-occlusion-opacity":            NumberType,
        // "line-opacity-transition":           TransitionType,
        // "line-color-transition":             TransitionType,
        // "line-translate-transition":         TransitionType,
        // "line-width-transition":             TransitionType,
        // "line-gap-width-transition":         TransitionType,
        // "line-offset-transition":            TransitionType,
        // "line-blur-transition":              TransitionType,
        // "line-trim-color-transition":        TransitionType,
        // "line-emissive-strength-transition": TransitionType,
        // "line-border-width-transition":      TransitionType,
        // "line-border-color-transition":      TransitionType,
        // "line-occlusion-opacity-transition": TransitionType
    }
}